name: Doc Vim generation

on:
  push:
    branches:
      - "master"
    paths:
      - "doc/data-explorer.nvim.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: data-explorer.nvim
          pandoc: "doc/data-explorer.nvim.md"
          version: "NVIM v0.11.3"
          toc: true
          description: "Data Explorer is a Neovim plugin that allows you to explore and visualize data files (.parquet, .csv, .tsv) directly within Neovim. Powered by DuckDB and Telescope."
          titledatepattern: "%Y %B %d"
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: true
          shiftheadinglevelby: 0
          incrementheadinglevelby: 0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate Vim doc"
          branch: ${{ github.head_ref }}
