name: Doc generation

on:
  push:
    branches:
      - "master"
    paths:
      - "doc/data-explorer.nvim.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: data-explorer.nvim
          pandoc: "doc/data-explorer.nvim.md"
          version: "NVIM v0.8.0"
          toc: true
          description: "Data Explorer is a Neovim plugin that allows you to explore and visualize data files (.parquet, .csv, .tsv) directly within Neovim."
          titledatepattern: "%Y %B %d"
          demojify: false
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: true
          shiftheadinglevelby: 0
          incrementheadinglevelby: 0
